server:
  port: 8081
spring:
  application:
    name: SpringCrawler
  datasource:
    url: jdbc:h2:./sehua/localfile/h2/db;AUTO_SERVER=TRUE
    username: root
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: h2
  h2:
    console:
      enabled: true

# mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml # 配置mapper.xml文件路径
  type-aliases-package: com.wangsheng.SpringCrawler.entity # 实体类包名
